import { Process } from '@components/process';
import '@styles/globals.css';
import ContextProvider from './context/Context';

export const metadata = {
  title: 'CIMA',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ scrollBehavior: 'smooth' }}>
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bw+Stretch:wght@800&display=swap" />
      </head>
      <body className='main'>
        <ContextProvider>
          <main className='app'>
            {children}
          </main>
        </ContextProvider>
      </body>
    </html>
  );
}
